<?php

return [
    'beats' => [
        'Manual'           => 'Manual',
        'AALAVAYAL'        => 'BALA',
        'ANNA SALAI'       => 'BALA',
        'BUSSTAND'         => 'SHRI MAHESHWARAN',
        'DETS-LOCAL-FG'    => 'NAGARAJ',
        'DETS-MAIN BAZAAR' => 'ASHIK',
        'FNR-LOCAL-FG'     => 'NAGARAJ',
        'FNR-MAIN BAZAAR'  => 'ASHIK',
        'INDRA NAGAR'      => 'SHRI MAHESHWARAN',
        'KARAIYUR'         => 'BALA',
        'KONNAIYUR'        => 'SHRI MAHESHWARAN',
        'KULIPIRAI'        => 'SHRI MAHESHWARAN',
        'MELATHANIYAM'     => 'BALA',
        'NACHANTHUPATTI'   => 'ASHIK',
        'NATTUKAL(PMV)'    => 'BALA',
        'PANAYAPATTI'      => 'NAGARAJ',
        'POOLANKURICHI'    => 'BALA',
        'PP-LOCAL-FG'      => 'NAGARAJ',
        'PP-MAIN BAZAAR'   => 'ASHIK',
        'PUDUR'            => 'SHRI MAHESHWARAN',
        'UDB DUMMY BEAT'   => 'NO SALES MAN',
        'VELANGUDI'        => 'NAGARAJ',
    ],



    'customers' => [

        'AALAVAYAL' => [
            'Amutham Medical',
            'Deva Store',
            'Sri Amman Janaral Store',
            'Jeeva Tea Stall',
            'Maharaja Store',
            'Kodangi Tea Stall',
            'Kanmani Petti Kadai',
            'Sri Bakkery',
            'Sri Oliyanayagi Amman Bakkery',
            'POOVA STD BOOTH',
            'AKILA ESWARI STORE',
            'SRI AMBAL MALIGAI',
            'SS STORE',
            'PANAIYAPPAN STORE',
            'PALANISAMY MALIGAI',
            'REVATHI MALIGAI',
            'Janani Stores',
            'LINGA MALIGAI',
            'K .R. MUTHU MALIGAI',
            'Selva Vinayaga Store',
            'Jana Store',
            'Sri Santhana Karuppar Maligai',
            'Sri Meenachi Maligai Store',
            'P.R.G Store',
            'Sasi Maligai',
            'THIRUVASAGAM TEA STALL',
            'OOM MEDICAL',
            'Sri Palani Andavar Medicals',
            'SRI AMBAL MEDICAL (AK)',
            'Amman Medicals',
            'Ranga Medical&General',
        ],

        'ANNA SALAI' => [
            'MKA Vetrivel Nagal Maliga & Electronics',
            'KARMEGAM MALIGAI STORE AND FANCY',
            'Star Bakkery',
            'New Friends Coffee Bar',
            'Rajamanickam Tea Stall',
            'MANI SUPER MARKET',
            'Muthu Lakshmi Store',
            'RENGANATHAN MALIGAI',
            'BHARATHI STORE',
            'Chinthamani Store',
            'Mahi Store',
            'Arumugam Store',
            'Ravi Malligai',
            'A. N. PL Malligai',
            'Sakthi Maligai',
            'BHANUMATHI KAFEA',
            'OM MURUGA MEDICAL',
            'Shri Arasumahan Medicals',
            'ANBUMANI MEDICALS',
        ],

        'BUSSTAND' => [
            'RAMJAN FANCY',
            'M.K.A VADIVEL FANCY STORE',
            'SRI MALAYANDI FANCY',
            'KANNAPIRAN BAKERY',
            'JAI TRADERS',
            'OVIYA STORE',
            'KARUPPAR MALIGAI',
            'ALANGARAM STORES',
            'N.K.S. MALIGAI',
            'PREETHI STORE',
            'RAMZAN VETTALAI KADAI',
            'VIKRAM MALIGAI',
            'VINAYAKA OIL MART',
            'AHASH MALIGAI',
            'A.S. MALIGAI',
            'PADMINI VILAS BAKERY & SWEETS.',
            'SAKTHI SARAN STORE',
            'ANDIYAPPAN MALIGAI',
            'KURUNJI STORE',
            'SS GRAND SUPER MARKET',
        ],

        'NACHANTHUPATTI' => [
            'Ammbal Fancy Store',
            'ADAIKAN TEA STALL',
            'Pandian Store',
            'Lakshmi Fancy Store',
            'SANGEETHAM SHOPPING & SUPER MARKET',
            'Ambal Store',
            'MR CHE',
            'S V S    MALIGAI',
            'KARTHIK OIL STORE',
            'R R Maligai',
            'ALAGU RICE',
            'RAJA RANI FANCY',
            'SENTHIL MALIGAI',
            'SUBBU STORE',
            'ADAIKALAM MALIGAI',
            'S. A. S TEA STALL',
            'BACKIA STORE',
            'LAKSHMI MALIGAI',
            'AIYA VEGETABLE SHOP',
            'Palaniyappan Maligai',
            'Muthu Dept. Store',
            'DHAYA  MEDICAL',
            'VINAYAGAR MEDICAL',
            'MUTHU MEENAKSHI MEDICAL',
            'THIRUPATHI MEDICAL',
            'Meenakshi Medicals',
            'ANGAYARKANNI MEDICAL',
            'SRI SAI CARE PHARMACY',
        ],

        'PANAYAPATTI' => [
            'Deepak Fancy And Novelties',
            'Sri Alagaperumal Bakery',
            'HARI HARASUTHAN SRORE',
            'RATHIKA FANCY',
            'SANGEETHAS BAKERY',
            'PALANI MEDICAL',
            'MADHU AMBAL MALIGAI',
            'MITHA MALIGAI STORE',
            'RAJINI MURUGAN BAKERY',
            'GANESHAN COOL BAR',
            'CHANDRAN STORE',
            'RAJA COOL DRINKS',
            'ALAGU  MALIGAI',
            'ARUL SELVAM MALIGAI',
            'MATHA MALIGAI',
            'SIVASAKTHI STORE',
            'ALAGAPPAN MALIGAI',
            'AKILANDESWARI STORE',
            'OM MURUGA MALIGAI',
            'ALAGU BROS',
            'Vetrikumaran Store',
            'Singaram Maligai',
            'PERUMAL DEVER',
            'Cinnaiyah Velar Maligai',
            'ANBU MALIGAI',
            'CHINNAIYA VELLAR MALIGAI',
        ],

        'VELANGUDI' => [
            'Cheran Maligai',
            'Niranjana Store',
            'Porkodi Tea And Tiffin',
            'Mekka Store',
            'AATHA STORE',
            'VALLI MURUGAPPA STORE',
            'JAYARAMAN MALIGAI',
            'FATHIMA STORE',
            'Om Sakthi Stores',
            'Captain Maligai',
            'Bismi Store',
            'Murugan Store',
            'IBRAHIM MALIGAI',
            'AK Sami Store',
            'BABYSRI STORE',
            'Marudharaj Maligai',
            'SMR Maligai',
            'Raja Store',
            'SLR Store',
            'Cena Mall',
            'VIP Super Market',
            'Ambal Maligai',
            'ANJUGA STORE',
            'Machakalai Store',
            'SUBBIAH MEDICALS',
            'Surya Medicals',
        ],

        // 'DETS-LOCAL-FG' => [
        //     'CHANDRASEKAR MALIGAI 1',
        //     'MODERN READYMADES',
        //     'PRIYA  BAKERY',
        //     'USHA LADIES CENTRE',
        //     'Asma  MALIGAI',
        //     'ANNAMALAI STORES',
        //     'SRI KRISHNA BAKERY',
        //     'T. R. Oil Store',
        //     'SRI RAM MEDICAL',
        //     'BAWA MEDICAL',
        //     'SELVARAJ AGENCY',
        //     'MANGALAM TRADERS',
        //     'PALANI MALIGAI',
        //     'INDIAN STORE',
        //     'M.SAMI & Co',
        //     'RAVICHANDRAN MALIGAI',
        //     'NIZAM TRADERS',
        //     'KAMACHI MALIGAI',
        // ],

        // 'DETS-MAIN BAZAAR' => [
        //     'SRI PONNAIYAH MALIGAI',
        //     'Anna Maligai',
        //     'PRABU STORE',
        //     'ABIRAMI  MEDICALS',
        //     'ARASU MEDICALS',
        //     'ANNAI MEDICAL',
        //     'ANBU MEDICAL  MART',
        //     'AATHIKALATHU ALANGARA MAALIGAI(PDKT)',
        //     'JOTHY STORE',
        //     'NIZAM STORE',
        //     'Lucky Store',
        //     'SRI  ABIRAMI  TRADERS',
        //     'SIVMANI STORE',
        //     'S.M.K STORES',
        //     'SIVASAKTHI STORES',
        // ],

        'KARAIYUR' => [
            'SNS Fancy',
            'Namma Idly & Tea Kadai',
            'Nachiyar Tea Stall',
            'Prasanna Maligai',
            'Nagajoothi Tea & Coffe Stall',
            'AAVIN',
            'Aavin Palagam',
            'KS Tea Stall',
            'PALANISAMY MALIGAI',
            'KVS STORE',
            'SIVA MALIGAI',
            'MAJEETH STORE',
            'MANIKKAM MALIGAI',
            'ABDUL JAFFAR MALIGAI',
            'SUNDARI MINI SUPERMART',
            'Mahalakshmi Store',
            'Chinniah Store',
            'Udhaya Maligai',
            'Aaradhana Maligai',
            'Rahman Maligai',
            'Sri Ponnalagu Maligai',
            'PLK Maligai',
            'Jinna Store',
            'Sabareesan Store',
            'Vel Murugan Medical',
            'Sri Kumaran Medical',
            'VINAYAKAR MEDICAL',
            'SRI MAHAMUNI MEDICALS',
            'CENA MAAL',
            'KARUPPUSAMY MALIGAI',
            'A.N.MALIGAI',
            'SADAM HUSSAIN MALIGAI',
        ],

        'KONNAIYUR' => [
            'Ismail Store',
            'KANAGA FANCY & CHAPPALS',
            'TKSS MALIGAI',
            'SONA MALLIGAI',
            'SRI AMMAN  STORE',
            'RVMB STORE',
            'AL RAHMAN STORE',
            'SELVA VINAYAGAR STORES',
            'K. K.R.MALIGAI',
            'VAIGARAI  STORE',
            'PALANIANDAVAR MALIGAI',
            'YOGAM MALIGAI',
            'VINAYAGA MEDICAL',
            'NARMATHA MEDICALS',
            'SAROJA PHARMACY',
            'APPLE MALLIGAI',
        ],

        'KULIPIRAI' => [
            'AVP Store',
            'ALAGAPPAN MALLIGAI STORE',
            'KAVITHA MALIGAI',
            'ARS STORE',
            'KAVERI AGENCEIS',
            'MAKKAL MARUNTHAGAM',
            'L .K . STORE',
            'OM SAKTHI MALIGAI',
            'NEW AVM STORE',
            'R A J MALIGAI',
            'ASHOKA MALIGAI',
            'KARPAGA VINAYAKAR STORE',
            'RAJAN BEEDA',
            'IYYAPPA MALIGAI',
            'GENGASWARAN MALIGAI',
            'VAIRAM MALIGAI',
            'Selvam Maligai',
            'KAILASAM MALIGAI',
            'VASANTHAMMAL MALIGAI',
            'SUBBAIAH MALIGAI',
            'Malaiyappa Maligai',
            'APPOLLO MEDICAL',
            'SRI SAKTHI MEDICAL',
            'NALLAPPA PHARMACY',
            'SREE LAKSHMI MEDICALS',
            'AMBAL MEDICAL',
            'RAHIM STORE',
            'Indirani Kannan Textiles',
            'JEEVA (SAKTHI PROJECT)',
            'KARPAGA VINAYAR STORE',
        ],

        'MELATHANIYAM' => [
            'Shri Ayyanar Bakery And Sweets',
            'Karunya Medicals',
            'Royal Store',
            'CITY FANCY',
            'Vadivel Tea Stall',
            'Thenmozhi',
            'Saravana Maligai',
            'UDAYAM STORE',
            'SK TRADERS',
            'DEEN MALIGAI',
            'ABDULLAH MALLIGAI',
            'RAMAIAH MALIGAI',
            'Murugan Store',
            'Shanmugam Store',
            'Adaikappan Maligai',
            'BMR Maligai Store',
            'Ulagammal Maligai',
            'Devaraj Maligai',
            'Balamurugan Maligai',
            'New Deen Maligai',
            'New Arumugam Maligai',
            'Almadheena Store',
            'Aadhi Yogith Malligai Store',
            'Arumugam Maligai',
            'Subramani Store',
            'LUCKY STORE',
            'ESMA Store',
            'SUGAM MEDICAL',
            'Amma Medical',
            'Sri Lakshmi Medical',
            'Sri Ambal Medical',
            'Rudhran Medical',
        ],

        'POOLANKURICHI' => [
            'Ramanathan Maliga',
            'Pride Pharmacy',
            'Palaniyappa Store',
            'Muthu Store',
            'HariS Store',
            'Ruthra Store',
            'TMR MALIGAI',
            'ARUMUGAM MALIGAI SHOP',
            'KANNA STORE',
            'KSA STORE',
            'BALASUBRAMANIYAN STORE',
            'BISMI STORE',
            'AACHI STORE',
            'AR Store',
            'KARUPAIH RICE MILL & MALIGAI',
            'PALANIYAPPA STORE',
            'MUTHU THANGAM STORE',
            'RAHUMAN MALIGAI',
        ],

        'PUDUR' => [
            'AAVIN PALAGAM',
            'NAVEEN SNACKS SHOP',
            'VPN STORE',
            'SRI SANTHANA KALAI OIL STORE AND MALIGAI STORE',
            'SRI SURAVALI AMMAN BAKERY',
            'A. L. S Store',
            'Vetrivel Maligai',
            'P R B STORE',
            'Periyanna MALIGAI',
            'PASUTHAM TEA STALL',
            'VINAYAGA SUPER MARKET',
            'PARANGI SUBBIAH TEA STALL',
            'PALANIANDAVAR STORE',
            'Dhinesh Maligai',
            'VINAYAGA MEDICAL',
            'MEENAKSHI MEDICAL',
        ],

        'NATTUKAL(PMV)' => [
            'Sri Murugan Agency',
            'Sri Coverings',
            'Bagavathi Amman Store',
            'PALANIYAPPAN MALIGAI',
            'PLS MALIGAI',
            'SRI Oliyanayaki Medical',
            'Sri Vetri Vinayagar Store',
            'Kannappar Maligai Thambi Kadai',
            'JAMES COOL BAR',
            'JEYALAKSHMI MALIGAI (NA)',
            'PALANI ANDAVAR MALIGAI',
            'BALAMURUGAN MALIGAI',
            'Sri Venkateshwara Metal Mart',
            'N.THIRUGNANAM MEDICALS & GENERAL MERCHANT',
            'MALAYANDI MEDICAL',
            'MUKIL STORE',
            'THIRUMAHAL STORE',
        ],

        'INDRA NAGAR' => [
            'Jannath Fancy Store',
            'ABDULLAH FANCY',
            'SREE SIVANTHI MATCHING CORNER',
            'KARUPPAIYA RICE STORE',
            'DHARSAN MALIGAI',
            'SARAVANA AGENCY',
            'S.N.S STORE',
            'RAMJAN AGENCY',
            'SIVA MALIGAI',
            'KALAI MATHI STORE',
            'ZAM ZAM MALIGAI',
            'Sri Mahalekshmi Store',
            'MAM STORE',
            'Al Amir Store',
            'MASHA ALLAH STORE',
            'JAI STORE',
            'NISHA STORE',
            'MURUGAPPAN TEA KADAI',
            'PL.A. SUPER MARKET',
            'AADHIL STORE',
            'Shivathi Silks',
            'ALAGU MEDICAL',
            'SIVANTI MEDICALS',
        ],

        'DETS-LOCAL-FG' => [
            'CHANDRASEKAR MALIGAI 1',
            'MODERN READYMADES',
            'PRIYA  BAKERY',
            'USHA LADIES CENTRE',
            'Asma  MALIGAI',
            'ANNAMALAI STORES',
            'SRI KRISHNA BAKERY',
            'T. R. Oil Store',
            'SELVARAJ AGENCY',
            'MANGALAM TRADERS',
            'PALANI MALIGAI',
            'INDIAN STORE',
            'M.SAMI & Co',
            'RAVICHANDRAN MALIGAI',
            'NIZAM TRADERS',
            'KAMACHI MALIGAI',
        ],

        'FNR-LOCAL-FG' => [
            'CHANDRASEKAR MALIGAI 1',
            'MODERN READYMADES',
            'PRIYA  BAKERY',
            'USHA LADIES CENTRE',
            'Asma  MALIGAI',
            'ANNAMALAI STORES',
            'SRI KRISHNA BAKERY',
            'T. R. Oil Store',
            'SELVARAJ AGENCY',
            'MANGALAM TRADERS',
            'PALANI MALIGAI',
            'INDIAN STORE',
            'M.SAMI & Co',
            'RAVICHANDRAN MALIGAI',
            'NIZAM TRADERS',
            'KAMACHI MALIGAI',
        ],

        'PP-LOCAL-FG' => [
            'CHANDRASEKAR MALIGAI 1',
            'MODERN READYMADES',
            'PRIYA  BAKERY',
            'USHA LADIES CENTRE',
            'Asma  MALIGAI',
            'ANNAMALAI STORES',
            'SRI KRISHNA BAKERY',
            'T. R. Oil Store',
            'SELVARAJ AGENCY',
            'MANGALAM TRADERS',
            'PALANI MALIGAI',
            'INDIAN STORE',
            'M.SAMI & Co',
            'RAVICHANDRAN MALIGAI',
            'NIZAM TRADERS',
            'KAMACHI MALIGAI',
        ],

        'DETS-MAIN BAZAAR' => [
            'SRI PONNAIYAH MALIGAI',
            'Anna Maligai',
            'PRABU STORE',
            'ABIRAMI  MEDICALS',
            'ARASU MEDICALS',
            'ANNAI MEDICAL',
            'ANBU MEDICAL  MART',
            'AATHIKALATHU ALANGARA MAALIGAI(PDKT)',
            'JOTHY STORE',
            'NIZAM STORE',
            'Lucky Store',
            'SIVMANI STORE',
            'S.M.K STORES',
            'SIVASAKTHI STORES',
            'SRI  ABIRAMI  TRADERS',
        ],

        'FNR-MAIN BAZAAR' => [
            'SRI PONNAIYAH MALIGAI',
            'Anna Maligai',
            'PRABU STORE',
            'ABIRAMI  MEDICALS',
            'ARASU MEDICALS',
            'ANNAI MEDICAL',
            'ANBU MEDICAL  MART',
            'AATHIKALATHU ALANGARA MAALIGAI(PDKT)',
            'JOTHY STORE',
            'NIZAM STORE',
            'Lucky Store',
            'SIVMANI STORE',
            'S.M.K STORES',
            'SIVASAKTHI STORES',
            'SRI  ABIRAMI  TRADERS',
        ],

        'PP-MAIN BAZAAR' => [
            'SRI PONNAIYAH MALIGAI',
            'Anna Maligai',
            'PRABU STORE',
            'ABIRAMI  MEDICALS',
            'ARASU MEDICALS',
            'ANNAI MEDICAL',
            'ANBU MEDICAL  MART',
            'AATHIKALATHU ALANGARA MAALIGAI(PDKT)',
            'JOTHY STORE',
            'NIZAM STORE',
            'Lucky Store',
            'SIVMANI STORE',
            'S.M.K STORES',
            'SIVASAKTHI STORES',
            'SRI  ABIRAMI  TRADERS',
        ],

],

];
